#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    if [ "$(readlink /etc/udev/rules.d/70-axidev-io-uinput.rules 2>/dev/null || true)" = "/dev/null" ]; then
        rm -f /etc/udev/rules.d/70-axidev-io-uinput.rules
    fi
    udevadm control --reload-rules >/dev/null 2>&1 || true
    udevadm trigger /dev/uinput >/dev/null 2>&1 || true
fi

#DEBHELPER#

exit 0
