#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    udevadm control --reload-rules >/dev/null 2>&1 || true
    udevadm trigger /dev/uinput >/dev/null 2>&1 || true
fi

#DEBHELPER#

exit 0
