from __future__ import annotations

from ..models import KeyDisplay, KeySpec


UNIT = 4
MAIN_BLOCK_WIDTH = 60
NAV_START = 64
NUMPAD_START = 80


def key(
    label: str,
    *,
    row: int,
    column: int,
    width: float = 1.0,
    height: int = 1,
    secondary_label: str | None = None,
    key_id: str | None = None,
    latchable: bool = False,
    io_key: str | None = None,
    latched_io_key: str | None = None,
    holds_when_latched: bool = False,
    honors_latched_modifiers: bool = True,
    display_variants: tuple[KeyDisplay, ...] = (),
) -> KeySpec:
    return KeySpec(
        label=label,
        row=row,
        column=column,
        width=width,
        height=height,
        secondary_label=secondary_label,
        key_id=key_id,
        latchable=latchable,
        io_key=io_key,
        latched_io_key=latched_io_key,
        holds_when_latched=holds_when_latched,
        honors_latched_modifiers=honors_latched_modifiers,
        display_variants=display_variants,
    )


def held_modifier(
    label: str,
    *,
    row: int,
    column: int,
    width: float,
    key_id: str,
    io_key: str,
    latched_io_key: str | None = None,
) -> KeySpec:
    return key(
        label,
        row=row,
        column=column,
        width=width,
        key_id=key_id,
        latchable=True,
        io_key=io_key,
        latched_io_key=latched_io_key or io_key,
        holds_when_latched=True,
        honors_latched_modifiers=False,
    )


def u(value: int) -> int:
    return value * UNIT


def shifted_key(
    label: str,
    shifted_label: str,
    *,
    row: int,
    column: int,
    width: float = 1.0,
    height: int = 1,
    key_id: str | None = None,
    latchable: bool = False,
    io_key: str | None = None,
    latched_io_key: str | None = None,
    holds_when_latched: bool = False,
    honors_latched_modifiers: bool = True,
) -> KeySpec:
    return key(
        label,
        row=row,
        column=column,
        width=width,
        height=height,
        key_id=key_id,
        latchable=latchable,
        io_key=io_key,
        latched_io_key=latched_io_key,
        holds_when_latched=holds_when_latched,
        honors_latched_modifiers=honors_latched_modifiers,
        display_variants=(
            KeyDisplay(
                label=shifted_label,
                requires_modifiers=frozenset({"shift"}),
            ),
        ),
    )


def build_us_iso_layout() -> list[KeySpec]:
    return [
        key("Esc", row=0, column=u(0), io_key="Escape"),
        key("F1", row=0, column=u(2)),
        key("F2", row=0, column=u(3)),
        key("F3", row=0, column=u(4)),
        key("F4", row=0, column=u(5)),
        key("F5", row=0, column=u(7)),
        key("F6", row=0, column=u(8)),
        key("F7", row=0, column=u(9)),
        key("F8", row=0, column=u(10)),
        key("F9", row=0, column=u(12)),
        key("F10", row=0, column=u(13)),
        key("F11", row=0, column=u(14)),
        key("F12", row=0, column=u(15)),
        key("PrtSc", row=0, column=NAV_START, io_key="PrintScreen"),
        key("ScrLk", row=0, column=NAV_START + u(1), io_key="ScrollLock"),
        key("Pause", row=0, column=NAV_START + u(2), io_key="Pause"),

        shifted_key("`", "~", row=1, column=u(0)),
        shifted_key("1", "!", row=1, column=u(1)),
        shifted_key("2", "@", row=1, column=u(2)),
        shifted_key("3", "#", row=1, column=u(3)),
        shifted_key("4", "$", row=1, column=u(4)),
        shifted_key("5", "%", row=1, column=u(5)),
        shifted_key("6", "^", row=1, column=u(6)),
        shifted_key("7", "&", row=1, column=u(7)),
        shifted_key("8", "*", row=1, column=u(8)),
        shifted_key("9", "(", row=1, column=u(9)),
        shifted_key("0", ")", row=1, column=u(10)),
        shifted_key("-", "_", row=1, column=u(11)),
        shifted_key("=", "+", row=1, column=u(12)),
        key("Backspace", row=1, column=u(13), width=2.0, io_key="Backspace"),
        key("Ins", row=1, column=NAV_START, io_key="Insert"),
        key("Home", row=1, column=NAV_START + u(1), io_key="Home"),
        key("PgUp", row=1, column=NAV_START + u(2), io_key="PageUp"),
        key("Num", row=1, column=NUMPAD_START, io_key="NumLock"),
        key("/", row=1, column=NUMPAD_START + u(1), io_key="NumpadDivide"),
        key("*", row=1, column=NUMPAD_START + u(2), io_key="NumpadMultiply"),
        key("-", row=1, column=NUMPAD_START + u(3), io_key="NumpadMinus"),

        key("Tab", row=2, column=u(0), width=1.5, io_key="Tab"),
        key("Q", row=2, column=6),
        key("W", row=2, column=10),
        key("E", row=2, column=14),
        key("R", row=2, column=18),
        key("T", row=2, column=22),
        key("Y", row=2, column=26),
        key("U", row=2, column=30),
        key("I", row=2, column=34),
        key("O", row=2, column=38),
        key("P", row=2, column=42),
        shifted_key("[", "{", row=2, column=46),
        shifted_key("]", "}", row=2, column=50),
        key("Del", row=2, column=NAV_START, io_key="Delete"),
        key("End", row=2, column=NAV_START + u(1), io_key="End"),
        key("PgDn", row=2, column=NAV_START + u(2), io_key="PageDown"),
        key("7", row=2, column=NUMPAD_START, secondary_label="Home", io_key="Numpad7"),
        key("8", row=2, column=NUMPAD_START + u(1), secondary_label="Up", io_key="Numpad8"),
        key("9", row=2, column=NUMPAD_START + u(2), secondary_label="PgUp", io_key="Numpad9"),
        key("+", row=2, column=NUMPAD_START + u(3), io_key="NumpadPlus", height=2),

        key("Caps", row=3, column=u(0), width=1.75, key_id="caps", latchable=True, io_key="CapsLock"),
        key("A", row=3, column=7),
        key("S", row=3, column=11),
        key("D", row=3, column=15),
        key("F", row=3, column=19),
        key("G", row=3, column=23),
        key("H", row=3, column=27),
        key("J", row=3, column=31),
        key("K", row=3, column=35),
        key("L", row=3, column=39),
        shifted_key(";", ":", row=3, column=43),
        shifted_key("'", '"', row=3, column=47),
        key("Enter", row=3, column=51, width=2.25, io_key="Enter"),
        key("4", row=3, column=NUMPAD_START, secondary_label="Left", io_key="Numpad4"),
        key("5", row=3, column=NUMPAD_START + u(1), io_key="Numpad5"),
        key("6", row=3, column=NUMPAD_START + u(2), secondary_label="Right", io_key="Numpad6"),

        held_modifier("Shift", row=4, column=u(0), width=1.25, key_id="shift", io_key="ShiftLeft"),
        shifted_key("\\", "|", row=4, column=5),
        key("Z", row=4, column=9),
        key("X", row=4, column=13),
        key("C", row=4, column=17),
        key("V", row=4, column=21),
        key("B", row=4, column=25),
        key("N", row=4, column=29),
        key("M", row=4, column=33),
        shifted_key(",", "<", row=4, column=37),
        shifted_key(".", ">", row=4, column=41),
        shifted_key("/", "?", row=4, column=45),
        held_modifier(
            "Shift",
            row=4,
            column=49,
            width=2.75,
            key_id="shift",
            io_key="ShiftRight",
            latched_io_key="ShiftLeft",
        ),
        key("Up", row=4, column=NAV_START + u(1), io_key="Up"),
        key("1", row=4, column=NUMPAD_START, secondary_label="End", io_key="Numpad1"),
        key("2", row=4, column=NUMPAD_START + u(1), secondary_label="Down", io_key="Numpad2"),
        key("3", row=4, column=NUMPAD_START + u(2), secondary_label="PgDn", io_key="Numpad3"),
        key("Enter", row=4, column=NUMPAD_START + u(3), io_key="NumpadEnter", height=2),

        held_modifier("Ctrl", row=5, column=u(0), width=1.25, key_id="ctrl", io_key="CtrlLeft"),
        held_modifier("Win", row=5, column=5, width=1.25, key_id="super", io_key="SuperLeft"),
        held_modifier("Alt", row=5, column=10, width=1.25, key_id="alt", io_key="AltLeft"),
        key("Space", row=5, column=15, width=6.25, io_key="Space"),
        held_modifier("AltGr", row=5, column=40, width=1.25, key_id="altgr", io_key="AltRight"),
        held_modifier(
            "Win",
            row=5,
            column=45,
            width=1.25,
            key_id="super",
            io_key="SuperRight",
            latched_io_key="SuperLeft",
        ),
        key("Menu", row=5, column=50, width=1.25, io_key="Menu"),
        held_modifier(
            "Ctrl",
            row=5,
            column=55,
            width=1.25,
            key_id="ctrl",
            io_key="CtrlRight",
            latched_io_key="CtrlLeft",
        ),
        key("Left", row=5, column=NAV_START, io_key="Left"),
        key("Down", row=5, column=NAV_START + u(1), io_key="Down"),
        key("Right", row=5, column=NAV_START + u(2), io_key="Right"),
        key("0", row=5, column=NUMPAD_START, width=2.0, secondary_label="Ins", io_key="Numpad0"),
        key(".", row=5, column=NUMPAD_START + u(2), secondary_label="Del", io_key="NumpadDecimal"),
    ]
