from __future__ import annotations

from ..models import KeySpec


def build_us_iso_layout() -> list[list[KeySpec]]:
    return [
        [
            KeySpec("`", secondary_label="~"),
            KeySpec("1", secondary_label="!"),
            KeySpec("2", secondary_label="@"),
            KeySpec("3", secondary_label="#"),
            KeySpec("4", secondary_label="$"),
            KeySpec("5", secondary_label="%"),
            KeySpec("6", secondary_label="^"),
            KeySpec("7", secondary_label="&"),
            KeySpec("8", secondary_label="*"),
            KeySpec("9", secondary_label="("),
            KeySpec("0", secondary_label=")"),
            KeySpec("-", secondary_label="_"),
            KeySpec("=", secondary_label="+"),
            KeySpec("Backspace", width=2.2, key_id="backspace", io_key="Backspace"),
        ],
        [
            KeySpec("Tab", width=1.7, key_id="tab", io_key="Tab"),
            KeySpec("Q"),
            KeySpec("W"),
            KeySpec("E"),
            KeySpec("R"),
            KeySpec("T"),
            KeySpec("Y"),
            KeySpec("U"),
            KeySpec("I"),
            KeySpec("O"),
            KeySpec("P"),
            KeySpec("[", secondary_label="{"),
            KeySpec("]", secondary_label="}"),
            KeySpec("\\", width=1.5, secondary_label="|"),
        ],
        [
            KeySpec("Caps", width=2.1, key_id="caps", latchable=True, io_key="CapsLock"),
            KeySpec("A"),
            KeySpec("S"),
            KeySpec("D"),
            KeySpec("F"),
            KeySpec("G"),
            KeySpec("H"),
            KeySpec("J"),
            KeySpec("K"),
            KeySpec("L"),
            KeySpec(";", secondary_label=":"),
            KeySpec("'", secondary_label='"'),
            KeySpec("Enter", width=2.6, key_id="enter", io_key="Enter"),
        ],
        [
            KeySpec(
                "Shift",
                width=2.6,
                key_id="shift",
                latchable=True,
                io_key="ShiftLeft",
                latched_io_key="ShiftLeft",
                holds_when_latched=True,
            ),
            KeySpec("<", secondary_label=">", io_key="LessThan"),
            KeySpec("Z"),
            KeySpec("X"),
            KeySpec("C"),
            KeySpec("V"),
            KeySpec("B"),
            KeySpec("N"),
            KeySpec("M"),
            KeySpec(",", secondary_label="<"),
            KeySpec(".", secondary_label=">"),
            KeySpec("/", secondary_label="?"),
            KeySpec(
                "Shift",
                width=3.0,
                key_id="shift",
                latchable=True,
                io_key="ShiftRight",
                latched_io_key="ShiftLeft",
                holds_when_latched=True,
            ),
        ],
        [
            KeySpec(
                "Ctrl",
                width=1.7,
                key_id="ctrl",
                latchable=True,
                io_key="CtrlLeft",
                latched_io_key="CtrlLeft",
                holds_when_latched=True,
                honors_latched_modifiers=False,
            ),
            KeySpec(
                "Alt",
                width=1.5,
                key_id="alt",
                latchable=True,
                io_key="AltLeft",
                latched_io_key="AltLeft",
                holds_when_latched=True,
                honors_latched_modifiers=False,
            ),
            KeySpec("Space", width=7.2, key_id="space", io_key="Space"),
            KeySpec(
                "AltGr",
                width=1.7,
                key_id="altgr",
                latchable=True,
                io_key="AltRight",
                latched_io_key="AltRight",
                holds_when_latched=True,
                honors_latched_modifiers=False,
            ),
            KeySpec("Left", width=1.4, key_id="left", io_key="Left"),
            KeySpec("Right", width=1.7, key_id="right", io_key="Right"),
        ],
    ]
