name: Build Artifacts

on:
  workflow_dispatch:

jobs:
  ubuntu:
    uses: ./.github/workflows/reusable-standalone-ubuntu.yml
    with:
      version-label: manual
      artifact-name: standalone-app-Ubuntu

  windows:
    uses: ./.github/workflows/reusable-standalone-windows.yml
    with:
      version-label: manual
      artifact-name: standalone-app-Windows
