name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ubuntu:
    uses: ./.github/workflows/reusable-check-ubuntu.yml

  windows:
    uses: ./.github/workflows/reusable-check-windows.yml
